update template etc

diff --git a/templates/default/dataloop-agent.erb b/templates/default/dataloop-agent.erb
--- a/templates/default/dataloop-agent.erb
+++ b/templates/default/dataloop-agent.erb
@@ -1,55 +1,82 @@
 #!/bin/sh
-
 ### BEGIN INIT INFO
-# Provides:          dataloop-agent
+# Provides:          Dataloop Agent
 # Required-Start:    $local_fs $network
-# Required-Stop:     $local_fs
+# Required-Stop:     $local_fs $network
 # Default-Start:     2 3 4 5
 # Default-Stop:      0 1 6
-# Short-Description: dataloop-agent
-# Description:       dataloop monitoring agent
+# Description:       Dataloop Agent
 ### END INIT INFO
 
-start () {
-  echo "dataloop agent started"
-  /usr/local/bin/dataloop-lin-agent \
-      --api-key <%= @api_key %> \
-      --tags    <%= @tags %> \
-      > /dev/null 2>&1 &
+API_KEY=<%= node[:dataloop][:agent][:api_key] %>
+SERVER=https://www.dataloop.io
+TAGS=<%= node[:dataloop][:node][:tags] %>
+SCRIPT="/usr/local/bin/dataloop-lin-agent --api-key $API_KEY --server $SERVER --tags $TAGS -d > /dev/null 2>&1"
+RUNAS=<%= node[:dataloop][:node][:user] %>
+
+PIDFILE=/var/run/dataloop-agent.pid
+LOGFILE=/var/log/dataloop/agent.log
+
+start() {
+  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
+    echo 'Service already running' >&2
+    return 1
+  fi
+  echo 'Starting service…' >&2
+  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
+  PID=$(su -c "$CMD" $RUNAS)
+  FORKPID=$((PID-1))
+  echo $FORKPID > $PIDFILE
+  echo 'Service started' >&2
 }
 
-stop () {
-  echo -n "dataloop agent: attempting deregister... "
-
-  /usr/local/bin/dataloop-lin-agent --api-key <%= @api_key %> \
-                                    --deregister
+stop() {
+  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
+    echo 'Service not running' >&2
+    return 1
+  fi
+  echo 'Stopping service…' >&2
 
   if [ $? -ne 0 ]; then
     echo "failed! "
-  else 
+  else
     echo "success"
   fi
 
-  pkill -9 -f 'dataloop-lin-agent'
   echo "dataloop agent stopped"
+  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
+  echo 'Service stopped' >&2
+
+  su -c "$SCRIPT --deregister" $RUNAS
+}
+
+uninstall() {
+  echo -n "Are you really sure you want to uninstall this service? That cannot be undone. [yes|No] "
+  local SURE
+  read SURE
+  if [ "$SURE" = "yes" ]; then
+    stop
+    rm -f "$PIDFILE"
+    echo "Notice: log file is not be removed: '$LOGFILE'" >&2
+    update-rc.d -f <NAME> remove
+    rm -fv "$0"
+  fi
 }
 
 case "$1" in
-start)
-        start
-        ;;
-stop)
-        stop
-        ;;
-restart)
-        stop
-        sleep 1
-        start
-        ;;
-*)
-        echo "Usage: $0 { start | stop | restart }"
-        exit 1
-        ;;
+  start)
+    start
+    ;;
+  stop)
+    stop
+    ;;
+  uninstall)
+    uninstall
+    ;;
+  restart)
+    stop
+    start
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|uninstall}"
 esac
-
-exit 0
